// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Container struct {
	ProjectID    string
	Name         string
	Image        string
	Url          string
	Ready        bool
	Reason       sql.NullString
	CreatedAt    string
	UpdatedAt    string
	Namespace    string
	Generation   int64
	CustomDomain sql.NullString
}

type IdentitySession struct {
	TokenHash string
	UserID    string
	CreatedAt string
	UpdatedAt string
	ExpiresAt string
}

type IdentityUser struct {
	ID           string
	Username     string
	PasswordHash string
	Email        sql.NullString
	Name         sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

type Operation struct {
	ID           string
	Status       string
	Error        sql.NullString
	CreatedAt    string
	UpdatedAt    string
	ResourceType sql.NullString
	ResourceName sql.NullString
	UserID       sql.NullString
	ProjectID    sql.NullString
}

type Project struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt string
}

type ProjectRepository struct {
	ProjectID        string
	UserID           string
	RepositoryOwner  string
	RepositoryName   string
	RepositoryBranch string
	ConnectedAt      string
	UpdatedAt        string
}
