// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Container struct {
	ProjectID  string
	Name       string
	Image      string
	Url        string
	Ready      bool
	Reason     sql.NullString
	CreatedAt  string
	UpdatedAt  string
	Namespace  string
	Generation int64
}

type Project struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt string
}
