// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOperation = `-- name: CreateOperation :one
INSERT INTO operations (id, status, resource_type, resource_name, user_id, project_id, created_at, updated_at)
VALUES ($1, 'pending', $2, $3, $4, $5, $6, $6)
RETURNING id, status, error, resource_type, resource_name, user_id, project_id, created_at, updated_at
`

type CreateOperationParams struct {
	ID           string
	ResourceType sql.NullString
	ResourceName sql.NullString
	UserID       sql.NullString
	ProjectID    sql.NullString
	CreatedAt    string
}

type CreateOperationRow struct {
	ID           string
	Status       string
	Error        sql.NullString
	ResourceType sql.NullString
	ResourceName sql.NullString
	UserID       sql.NullString
	ProjectID    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) CreateOperation(ctx context.Context, arg CreateOperationParams) (CreateOperationRow, error) {
	row := q.db.QueryRowContext(ctx, createOperation,
		arg.ID,
		arg.ResourceType,
		arg.ResourceName,
		arg.UserID,
		arg.ProjectID,
		arg.CreatedAt,
	)
	var i CreateOperationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.ResourceType,
		&i.ResourceName,
		&i.UserID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, name, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, name) DO NOTHING
RETURNING id, user_id, name, created_at
`

type CreateProjectParams struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContainer = `-- name: DeleteContainer :execrows
DELETE FROM containers
WHERE project_id = $1 AND name = $2
`

type DeleteContainerParams struct {
	ProjectID string
	Name      string
}

func (q *Queries) DeleteContainer(ctx context.Context, arg DeleteContainerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContainer, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE user_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getContainer = `-- name: GetContainer :one
SELECT project_id, name, image, url, ready, reason, created_at, updated_at, namespace, generation, custom_domain
FROM containers
WHERE project_id = $1 AND name = $2
`

type GetContainerParams struct {
	ProjectID string
	Name      string
}

func (q *Queries) GetContainer(ctx context.Context, arg GetContainerParams) (Container, error) {
	row := q.db.QueryRowContext(ctx, getContainer, arg.ProjectID, arg.Name)
	var i Container
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Image,
		&i.Url,
		&i.Ready,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespace,
		&i.Generation,
		&i.CustomDomain,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT id, status, error, resource_type, resource_name, user_id, project_id, created_at, updated_at
FROM operations
WHERE id = $1
`

type GetOperationRow struct {
	ID           string
	Status       string
	Error        sql.NullString
	ResourceType sql.NullString
	ResourceName sql.NullString
	UserID       sql.NullString
	ProjectID    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) GetOperation(ctx context.Context, id string) (GetOperationRow, error) {
	row := q.db.QueryRowContext(ctx, getOperation, id)
	var i GetOperationRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.Error,
		&i.ResourceType,
		&i.ResourceName,
		&i.UserID,
		&i.ProjectID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContainers = `-- name: ListContainers :many
SELECT project_id, name, image, url, ready, reason, created_at, updated_at, namespace, generation, custom_domain
FROM containers
WHERE project_id = $1
ORDER BY created_at, name
`

func (q *Queries) ListContainers(ctx context.Context, projectID string) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, listContainers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.Image,
			&i.Url,
			&i.Ready,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Namespace,
			&i.Generation,
			&i.CustomDomain,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingOperationsByResourceType = `-- name: ListPendingOperationsByResourceType :many
SELECT id, status, error, resource_type, resource_name, user_id, project_id, created_at, updated_at
FROM operations
WHERE status = 'pending' AND resource_type = $1
`

type ListPendingOperationsByResourceTypeRow struct {
	ID           string
	Status       string
	Error        sql.NullString
	ResourceType sql.NullString
	ResourceName sql.NullString
	UserID       sql.NullString
	ProjectID    sql.NullString
	CreatedAt    string
	UpdatedAt    string
}

func (q *Queries) ListPendingOperationsByResourceType(ctx context.Context, resourceType sql.NullString) ([]ListPendingOperationsByResourceTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listPendingOperationsByResourceType, resourceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingOperationsByResourceTypeRow
	for rows.Next() {
		var i ListPendingOperationsByResourceTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.Error,
			&i.ResourceType,
			&i.ResourceName,
			&i.UserID,
			&i.ProjectID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, created_at
FROM projects
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS (
    SELECT 1
    FROM projects
    WHERE user_id = $1 AND id = $2
)
`

type ProjectExistsParams struct {
	UserID string
	ID     string
}

func (q *Queries) ProjectExists(ctx context.Context, arg ProjectExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExists, arg.UserID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateContainerDomain = `-- name: UpdateContainerDomain :execrows
UPDATE containers SET custom_domain = $3, updated_at = $4
WHERE project_id = $1 AND name = $2
`

type UpdateContainerDomainParams struct {
	ProjectID    string
	Name         string
	CustomDomain sql.NullString
	UpdatedAt    string
}

func (q *Queries) UpdateContainerDomain(ctx context.Context, arg UpdateContainerDomainParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateContainerDomain,
		arg.ProjectID,
		arg.Name,
		arg.CustomDomain,
		arg.UpdatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateOperation = `-- name: UpdateOperation :exec
UPDATE operations
SET status = $2, error = $3, updated_at = $4
WHERE id = $1
`

type UpdateOperationParams struct {
	ID        string
	Status    string
	Error     sql.NullString
	UpdatedAt string
}

func (q *Queries) UpdateOperation(ctx context.Context, arg UpdateOperationParams) error {
	_, err := q.db.ExecContext(ctx, updateOperation,
		arg.ID,
		arg.Status,
		arg.Error,
		arg.UpdatedAt,
	)
	return err
}

const upsertContainer = `-- name: UpsertContainer :one
INSERT INTO containers (
    project_id, name, image, url, ready, reason,
    created_at, updated_at, namespace, generation
)
VALUES ($1, $2, $3, $4, TRUE, $5, $6, $7, $8, 1)
ON CONFLICT (project_id, name) DO UPDATE SET
    image = EXCLUDED.image,
    url = EXCLUDED.url,
    ready = EXCLUDED.ready,
    reason = EXCLUDED.reason,
    updated_at = EXCLUDED.updated_at,
    namespace = EXCLUDED.namespace,
    generation = containers.generation + 1
RETURNING project_id, name, image, url, ready, reason, created_at, updated_at, namespace, generation, custom_domain
`

type UpsertContainerParams struct {
	ProjectID string
	Name      string
	Image     string
	Url       string
	Reason    sql.NullString
	CreatedAt string
	UpdatedAt string
	Namespace string
}

func (q *Queries) UpsertContainer(ctx context.Context, arg UpsertContainerParams) (Container, error) {
	row := q.db.QueryRowContext(ctx, upsertContainer,
		arg.ProjectID,
		arg.Name,
		arg.Image,
		arg.Url,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Namespace,
	)
	var i Container
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Image,
		&i.Url,
		&i.Ready,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespace,
		&i.Generation,
		&i.CustomDomain,
	)
	return i, err
}
