// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, user_id, name, created_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, name) DO NOTHING
RETURNING id, user_id, name, created_at
`

type CreateProjectParams struct {
	ID        string
	UserID    string
	Name      string
	CreatedAt string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRowContext(ctx, createProject,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteContainer = `-- name: DeleteContainer :execrows
DELETE FROM containers
WHERE project_id = $1 AND name = $2
`

type DeleteContainerParams struct {
	ProjectID string
	Name      string
}

func (q *Queries) DeleteContainer(ctx context.Context, arg DeleteContainerParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteContainer, arg.ProjectID, arg.Name)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteProject = `-- name: DeleteProject :execrows
DELETE FROM projects
WHERE user_id = $1 AND id = $2
`

type DeleteProjectParams struct {
	UserID string
	ID     string
}

func (q *Queries) DeleteProject(ctx context.Context, arg DeleteProjectParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteProject, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const listContainers = `-- name: ListContainers :many
SELECT project_id, name, image, url, ready, reason, created_at, updated_at, namespace, generation
FROM containers
WHERE project_id = $1
ORDER BY created_at, name
`

func (q *Queries) ListContainers(ctx context.Context, projectID string) ([]Container, error) {
	rows, err := q.db.QueryContext(ctx, listContainers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Container
	for rows.Next() {
		var i Container
		if err := rows.Scan(
			&i.ProjectID,
			&i.Name,
			&i.Image,
			&i.Url,
			&i.Ready,
			&i.Reason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Namespace,
			&i.Generation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, user_id, name, created_at
FROM projects
WHERE user_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListProjects(ctx context.Context, userID string) ([]Project, error) {
	rows, err := q.db.QueryContext(ctx, listProjects, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectExists = `-- name: ProjectExists :one
SELECT EXISTS (
    SELECT 1
    FROM projects
    WHERE user_id = $1 AND id = $2
)
`

type ProjectExistsParams struct {
	UserID string
	ID     string
}

func (q *Queries) ProjectExists(ctx context.Context, arg ProjectExistsParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, projectExists, arg.UserID, arg.ID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const upsertContainer = `-- name: UpsertContainer :one
INSERT INTO containers (
    project_id, name, image, url, ready, reason,
    created_at, updated_at, namespace, generation
)
VALUES ($1, $2, $3, $4, TRUE, $5, $6, $7, $8, 1)
ON CONFLICT (project_id, name) DO UPDATE SET
    image = EXCLUDED.image,
    url = EXCLUDED.url,
    ready = EXCLUDED.ready,
    reason = EXCLUDED.reason,
    updated_at = EXCLUDED.updated_at,
    namespace = EXCLUDED.namespace,
    generation = containers.generation + 1
RETURNING project_id, name, image, url, ready, reason, created_at, updated_at, namespace, generation
`

type UpsertContainerParams struct {
	ProjectID string
	Name      string
	Image     string
	Url       string
	Reason    sql.NullString
	CreatedAt string
	UpdatedAt string
	Namespace string
}

func (q *Queries) UpsertContainer(ctx context.Context, arg UpsertContainerParams) (Container, error) {
	row := q.db.QueryRowContext(ctx, upsertContainer,
		arg.ProjectID,
		arg.Name,
		arg.Image,
		arg.Url,
		arg.Reason,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Namespace,
	)
	var i Container
	err := row.Scan(
		&i.ProjectID,
		&i.Name,
		&i.Image,
		&i.Url,
		&i.Ready,
		&i.Reason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Namespace,
		&i.Generation,
	)
	return i, err
}
