apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dcloud.fullname" . }}-console-nginx
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: console
data:
  default.conf: |
    server {
      listen 8080;
      server_name {{ .Values.console.publicHostname | quote }};

      root /usr/share/nginx/html;
      index index.html;

      location / {
        try_files $uri $uri/ /index.html;
      }

      location /api/ {
        proxy_pass http://{{ include "dcloud.fullname" . }}-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      }

      location /container/ {
        proxy_pass http://{{ include "dcloud.fullname" . }}-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      }

    }

    server {
      listen 8080;
      server_name ~^(?!{{ first (splitList "." .Values.console.publicHostname) }}$)[a-z0-9-]+\.{{ .Values.console.publicServiceDomain | replace "." "\\." }}$;

      location / {
        proxy_pass http://{{ include "dcloud.fullname" . }}-api:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
      }
    }
