apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dcloud.fullname" . }}-database
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
stringData:
  password: {{ .Values.database.auth.password | quote }}
  postgres-password: {{ .Values.database.auth.password | quote }}
  pgpool-password: {{ .Values.database.auth.password | quote }}
  repmgr-password: {{ .Values.database.auth.repmgrPassword | quote }}
  DCLD_DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql-ha-pgpool:%d/%s?sslmode=disable" .Values.database.auth.username .Values.database.auth.password (include "dcloud.fullname" .) (.Values.database.service.port | int) .Values.database.auth.database | quote }}
  DCLD_DATABASE_MIGRATION_URL: {{ printf "postgresql://%s:%s@%s-postgresql-ha-postgresql:%d/%s?sslmode=disable" .Values.database.auth.username .Values.database.auth.password (include "dcloud.fullname" .) (.Values.database.service.port | int) .Values.database.auth.database | quote }}
