apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "dcloud.fullname" . }}-internal
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: internal
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dcloud.fullname" . }}-internal
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: internal
rules:
  - apiGroups: ["serving.knative.dev"]
    resources: ["services", "services/status", "domainmappings", "domainmappings/status"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dcloud.fullname" . }}-internal
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: internal
subjects:
  - kind: ServiceAccount
    name: {{ include "dcloud.fullname" . }}-internal
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dcloud.fullname" . }}-internal
