apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dcloud.fullname" . }}-project
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: project
spec:
  replicas: {{ .Values.project.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: project
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: project
    spec:
      containers:
        - name: project
          image: {{ include "dcloud.image" (dict "root" . "repository" .Values.project.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - secretRef:
                name: {{ include "dcloud.fullname" . }}-database
          ports:
            - name: grpc
              containerPort: {{ .Values.project.service.port }}
          readinessProbe:
            tcpSocket:
              port: grpc
          livenessProbe:
            tcpSocket:
              port: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dcloud.fullname" . }}-project
  labels:
    {{- include "dcloud.labels" . | nindent 4 }}
    app.kubernetes.io/component: project
spec:
  ports:
    - name: grpc
      port: {{ .Values.project.service.port }}
      targetPort: grpc
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: project
