// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: container.proto

package containerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_container_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{0}
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_container_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{1}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Service       string                 `protobuf:"bytes,2,opt,name=service,proto3" json:"service,omitempty"`
	Timestamp     string                 `protobuf:"bytes,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_container_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{2}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *HealthResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Service struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image              string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Url                string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Ready              bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`
	Reason             string                 `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt          string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt          string                 `protobuf:"bytes,7,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Namespace          string                 `protobuf:"bytes,8,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ProjectId          string                 `protobuf:"bytes,9,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Generation         int64                  `protobuf:"varint,10,opt,name=generation,proto3" json:"generation,omitempty"`
	CustomDomain       string                 `protobuf:"bytes,11,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`
	DomainStatus       string                 `protobuf:"bytes,12,opt,name=domain_status,json=domainStatus,proto3" json:"domain_status,omitempty"`
	DomainStatusReason string                 `protobuf:"bytes,13,opt,name=domain_status_reason,json=domainStatusReason,proto3" json:"domain_status_reason,omitempty"`
	DomainCnameTarget  string                 `protobuf:"bytes,14,opt,name=domain_cname_target,json=domainCnameTarget,proto3" json:"domain_cname_target,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_container_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{3}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Service) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Service) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Service) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Service) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Service) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Service) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Service) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *Service) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *Service) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

func (x *Service) GetDomainStatus() string {
	if x != nil {
		return x.DomainStatus
	}
	return ""
}

func (x *Service) GetDomainStatusReason() string {
	if x != nil {
		return x.DomainStatusReason
	}
	return ""
}

func (x *Service) GetDomainCnameTarget() string {
	if x != nil {
		return x.DomainCnameTarget
	}
	return ""
}

type ListServicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_container_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{4}
}

func (x *ListServicesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListServicesRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Namespace     string                 `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Containers    []*Service             `protobuf:"bytes,4,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_container_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{5}
}

func (x *ListServicesResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListServicesResponse) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *ListServicesResponse) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ListServicesResponse) GetContainers() []*Service {
	if x != nil {
		return x.Containers
	}
	return nil
}

type DeployServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Port          int32                  `protobuf:"varint,5,opt,name=port,proto3" json:"port,omitempty"`
	MinScale      int32                  `protobuf:"varint,6,opt,name=min_scale,json=minScale,proto3" json:"min_scale,omitempty"`
	MaxScale      int32                  `protobuf:"varint,7,opt,name=max_scale,json=maxScale,proto3" json:"max_scale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployServiceRequest) Reset() {
	*x = DeployServiceRequest{}
	mi := &file_container_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployServiceRequest) ProtoMessage() {}

func (x *DeployServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployServiceRequest.ProtoReflect.Descriptor instead.
func (*DeployServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{6}
}

func (x *DeployServiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeployServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeployServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeployServiceRequest) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *DeployServiceRequest) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *DeployServiceRequest) GetMinScale() int32 {
	if x != nil {
		return x.MinScale
	}
	return 0
}

func (x *DeployServiceRequest) GetMaxScale() int32 {
	if x != nil {
		return x.MaxScale
	}
	return 0
}

type DeployServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeployServiceResponse) Reset() {
	*x = DeployServiceResponse{}
	mi := &file_container_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeployServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeployServiceResponse) ProtoMessage() {}

func (x *DeployServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeployServiceResponse.ProtoReflect.Descriptor instead.
func (*DeployServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{7}
}

func (x *DeployServiceResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

type DeleteServiceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceRequest) Reset() {
	*x = DeleteServiceRequest{}
	mi := &file_container_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceRequest) ProtoMessage() {}

func (x *DeleteServiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceRequest.ProtoReflect.Descriptor instead.
func (*DeleteServiceRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteServiceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *DeleteServiceRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DeleteServiceRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteServiceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServiceResponse) Reset() {
	*x = DeleteServiceResponse{}
	mi := &file_container_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServiceResponse) ProtoMessage() {}

func (x *DeleteServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServiceResponse.ProtoReflect.Descriptor instead.
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServiceResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_container_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{10}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_container_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{11}
}

func (x *GetOperationResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *GetOperationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetOperationResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type SetServiceDomainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProjectId     string                 `protobuf:"bytes,2,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	CustomDomain  string                 `protobuf:"bytes,4,opt,name=custom_domain,json=customDomain,proto3" json:"custom_domain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceDomainRequest) Reset() {
	*x = SetServiceDomainRequest{}
	mi := &file_container_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceDomainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceDomainRequest) ProtoMessage() {}

func (x *SetServiceDomainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceDomainRequest.ProtoReflect.Descriptor instead.
func (*SetServiceDomainRequest) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{12}
}

func (x *SetServiceDomainRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SetServiceDomainRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *SetServiceDomainRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetServiceDomainRequest) GetCustomDomain() string {
	if x != nil {
		return x.CustomDomain
	}
	return ""
}

type SetServiceDomainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       *Service               `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetServiceDomainResponse) Reset() {
	*x = SetServiceDomainResponse{}
	mi := &file_container_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetServiceDomainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetServiceDomainResponse) ProtoMessage() {}

func (x *SetServiceDomainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_container_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetServiceDomainResponse.ProtoReflect.Descriptor instead.
func (*SetServiceDomainResponse) Descriptor() ([]byte, []int) {
	return file_container_proto_rawDescGZIP(), []int{13}
}

func (x *SetServiceDomainResponse) GetService() *Service {
	if x != nil {
		return x.Service
	}
	return nil
}

var File_container_proto protoreflect.FileDescriptor

const file_container_proto_rawDesc = "" +
	"\n" +
	"\x0fcontainer.proto\x12\x13dcloud.container.v1\"\a\n" +
	"\x05Empty\"\x0f\n" +
	"\rHealthRequest\"`\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aservice\x18\x02 \x01(\tR\aservice\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\tR\ttimestamp\"\xba\x03\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\a \x01(\tR\tupdatedAt\x12\x1c\n" +
	"\tnamespace\x18\b \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"project_id\x18\t \x01(\tR\tprojectId\x12\x1e\n" +
	"\n" +
	"generation\x18\n" +
	" \x01(\x03R\n" +
	"generation\x12#\n" +
	"\rcustom_domain\x18\v \x01(\tR\fcustomDomain\x12#\n" +
	"\rdomain_status\x18\f \x01(\tR\fdomainStatus\x120\n" +
	"\x14domain_status_reason\x18\r \x01(\tR\x12domainStatusReason\x12.\n" +
	"\x13domain_cname_target\x18\x0e \x01(\tR\x11domainCnameTarget\"M\n" +
	"\x13ListServicesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\"\xaa\x01\n" +
	"\x14ListServicesResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x1c\n" +
	"\tnamespace\x18\x03 \x01(\tR\tnamespace\x12<\n" +
	"\n" +
	"containers\x18\x04 \x03(\v2\x1c.dcloud.container.v1.ServiceR\n" +
	"containers\"\xc6\x01\n" +
	"\x14DeployServiceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\x12\x12\n" +
	"\x04port\x18\x05 \x01(\x05R\x04port\x12\x1b\n" +
	"\tmin_scale\x18\x06 \x01(\x05R\bminScale\x12\x1b\n" +
	"\tmax_scale\x18\a \x01(\x05R\bmaxScale\"O\n" +
	"\x15DeployServiceResponse\x126\n" +
	"\aservice\x18\x01 \x01(\v2\x1c.dcloud.container.v1.ServiceR\aservice\"b\n" +
	"\x14DeleteServiceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\":\n" +
	"\x15DeleteServiceResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"g\n" +
	"\x14GetOperationResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x8a\x01\n" +
	"\x17SetServiceDomainRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"project_id\x18\x02 \x01(\tR\tprojectId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rcustom_domain\x18\x04 \x01(\tR\fcustomDomain\"R\n" +
	"\x18SetServiceDomainResponse\x126\n" +
	"\aservice\x18\x01 \x01(\v2\x1c.dcloud.container.v1.ServiceR\aservice2\xf0\x04\n" +
	"\x10ContainerService\x12Q\n" +
	"\x06Health\x12\".dcloud.container.v1.HealthRequest\x1a#.dcloud.container.v1.HealthResponse\x12c\n" +
	"\fListServices\x12(.dcloud.container.v1.ListServicesRequest\x1a).dcloud.container.v1.ListServicesResponse\x12f\n" +
	"\rDeployService\x12).dcloud.container.v1.DeployServiceRequest\x1a*.dcloud.container.v1.DeployServiceResponse\x12f\n" +
	"\rDeleteService\x12).dcloud.container.v1.DeleteServiceRequest\x1a*.dcloud.container.v1.DeleteServiceResponse\x12c\n" +
	"\fGetOperation\x12(.dcloud.container.v1.GetOperationRequest\x1a).dcloud.container.v1.GetOperationResponse\x12o\n" +
	"\x10SetServiceDomain\x12,.dcloud.container.v1.SetServiceDomainRequest\x1a-.dcloud.container.v1.SetServiceDomainResponseBDZBgithub.com/daigo-suhara/dcloud/internal/pb/containerpb;containerpbb\x06proto3"

var (
	file_container_proto_rawDescOnce sync.Once
	file_container_proto_rawDescData []byte
)

func file_container_proto_rawDescGZIP() []byte {
	file_container_proto_rawDescOnce.Do(func() {
		file_container_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)))
	})
	return file_container_proto_rawDescData
}

var file_container_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_container_proto_goTypes = []any{
	(*Empty)(nil),                    // 0: dcloud.container.v1.Empty
	(*HealthRequest)(nil),            // 1: dcloud.container.v1.HealthRequest
	(*HealthResponse)(nil),           // 2: dcloud.container.v1.HealthResponse
	(*Service)(nil),                  // 3: dcloud.container.v1.Service
	(*ListServicesRequest)(nil),      // 4: dcloud.container.v1.ListServicesRequest
	(*ListServicesResponse)(nil),     // 5: dcloud.container.v1.ListServicesResponse
	(*DeployServiceRequest)(nil),     // 6: dcloud.container.v1.DeployServiceRequest
	(*DeployServiceResponse)(nil),    // 7: dcloud.container.v1.DeployServiceResponse
	(*DeleteServiceRequest)(nil),     // 8: dcloud.container.v1.DeleteServiceRequest
	(*DeleteServiceResponse)(nil),    // 9: dcloud.container.v1.DeleteServiceResponse
	(*GetOperationRequest)(nil),      // 10: dcloud.container.v1.GetOperationRequest
	(*GetOperationResponse)(nil),     // 11: dcloud.container.v1.GetOperationResponse
	(*SetServiceDomainRequest)(nil),  // 12: dcloud.container.v1.SetServiceDomainRequest
	(*SetServiceDomainResponse)(nil), // 13: dcloud.container.v1.SetServiceDomainResponse
}
var file_container_proto_depIdxs = []int32{
	3,  // 0: dcloud.container.v1.ListServicesResponse.containers:type_name -> dcloud.container.v1.Service
	3,  // 1: dcloud.container.v1.DeployServiceResponse.service:type_name -> dcloud.container.v1.Service
	3,  // 2: dcloud.container.v1.SetServiceDomainResponse.service:type_name -> dcloud.container.v1.Service
	1,  // 3: dcloud.container.v1.ContainerService.Health:input_type -> dcloud.container.v1.HealthRequest
	4,  // 4: dcloud.container.v1.ContainerService.ListServices:input_type -> dcloud.container.v1.ListServicesRequest
	6,  // 5: dcloud.container.v1.ContainerService.DeployService:input_type -> dcloud.container.v1.DeployServiceRequest
	8,  // 6: dcloud.container.v1.ContainerService.DeleteService:input_type -> dcloud.container.v1.DeleteServiceRequest
	10, // 7: dcloud.container.v1.ContainerService.GetOperation:input_type -> dcloud.container.v1.GetOperationRequest
	12, // 8: dcloud.container.v1.ContainerService.SetServiceDomain:input_type -> dcloud.container.v1.SetServiceDomainRequest
	2,  // 9: dcloud.container.v1.ContainerService.Health:output_type -> dcloud.container.v1.HealthResponse
	5,  // 10: dcloud.container.v1.ContainerService.ListServices:output_type -> dcloud.container.v1.ListServicesResponse
	7,  // 11: dcloud.container.v1.ContainerService.DeployService:output_type -> dcloud.container.v1.DeployServiceResponse
	9,  // 12: dcloud.container.v1.ContainerService.DeleteService:output_type -> dcloud.container.v1.DeleteServiceResponse
	11, // 13: dcloud.container.v1.ContainerService.GetOperation:output_type -> dcloud.container.v1.GetOperationResponse
	13, // 14: dcloud.container.v1.ContainerService.SetServiceDomain:output_type -> dcloud.container.v1.SetServiceDomainResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_container_proto_init() }
func file_container_proto_init() {
	if File_container_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_container_proto_rawDesc), len(file_container_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_container_proto_goTypes,
		DependencyIndexes: file_container_proto_depIdxs,
		MessageInfos:      file_container_proto_msgTypes,
	}.Build()
	File_container_proto = out.File
	file_container_proto_goTypes = nil
	file_container_proto_depIdxs = nil
}
