apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "dcp.fullname" . }}-cloudrun
  labels:
    {{- include "dcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: cloudrun
    networking.knative.dev/visibility: cluster-local
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=false
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: cloudrun
    spec:
      containers:
        - name: cloudrun
          image: {{ include "dcp.image" (dict "root" . "repository" .Values.cloudrun.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.cloudrun.service.port }}
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.cloudrun.service.port }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.cloudrun.service.port }}
