apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: {{ include "dcp.fullname" . }}-container-apps
  labels:
    {{- include "dcp.labels" . | nindent 4 }}
    app.kubernetes.io/component: container-apps
    networking.knative.dev/visibility: cluster-local
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true,Replace=false
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: container-apps
    spec:
      enableServiceLinks: false
      timeoutSeconds: 300
      containers:
        - name: container-apps
          image: {{ include "dcp.image" (dict "root" . "repository" .Values.containerApps.image.repository) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources: {}
          ports:
            - containerPort: {{ .Values.containerApps.service.port }}
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /readyz
              port: {{ .Values.containerApps.service.port }}
            successThreshold: 1
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.containerApps.service.port }}
