image:
  registry: ghcr.io
  repositoryOwner: daigo-suhara
  pullPolicy: Always
  tag: latest

publicServiceDomain: drkatana.com

identity:
  replicaCount: 2
  image:
    repository: identity
  service:
    port: 8083

compute:
  replicaCount: 2
  image:
    repository: compute
  service:
    port: 8084

storage:
  createClass: true
  className: ceph-rbd
  clusterID: rook-ceph
  pool: rbd

console:
  replicaCount: 2
  image:
    repository: console
  service:
    type: LoadBalancer
    port: 8080
  publicServiceDomain: drkatana.com
  publicHostname: cloud.daigo-suhara.com

api:
  replicaCount: 2
  image:
    repository: api
  service:
    port: 8000

project:
  replicaCount: 2
  image:
    repository: project
  service:
    port: 8081

container:
  replicaCount: 2
  image:
    repository: container
  service:
    port: 8082

database:
  service:
    port: 5432
  auth:
    database: dcloud
    username: dcloud

postgresql-ha:
  global:
    security:
      allowInsecureImages: true
    defaultStorageClass: ceph-rbd
    postgresql:
      username: dcloud
      database: dcloud
      existingSecret: dcloud-database
      repmgrUsername: repmgr
    pgpool:
      existingSecret: dcloud-database
  postgresql:
    image:
      repository: soldevelo/postgresql-repmgr
      tag: 17.6.0-debian-12-r0
    database: dcloud
    username: dcloud
    replicaCount: 2
    existingSecret: dcloud-database
    persistence:
      storageClass: ceph-rbd
  pgpool:
    image:
      repository: soldevelo/pgpool
      tag: 4.6.3-debian-12-r0
