image:
  registry: ghcr.io
  repositoryOwner: daigo-suhara
  pullPolicy: Always
  tag: latest

publicServiceDomain: drkatana.com

identity:
  replicaCount: 2
  image:
    repository: identity
  service:
    port: 8083

storage:
  createClass: true
  className: ceph-rbd
  clusterID: rook-ceph
  pool: rbd

console:
  replicaCount: 2
  image:
    repository: console
  service:
    type: LoadBalancer
    port: 8080
  publicServiceDomain: drkatana.com
  publicHostname: cloud.daigo-suhara.com

api:
  replicaCount: 2
  image:
    repository: api
  service:
    port: 8000

project:
  replicaCount: 2
  image:
    repository: project
  service:
    port: 8081

container:
  replicaCount: 2
  image:
    repository: container
  service:
    port: 8082

database:
  service:
    port: 5432
  auth:
    database: dcloud
    username: dcloud
    password: dcloud-database-password-please-change
    repmgrPassword: dcloud-repmgr-password-please-change

postgresql-ha:
  global:
    defaultStorageClass: ceph-rbd
    postgresql:
      username: dcloud
      database: dcloud
      password: dcloud-database-password-please-change
      repmgrPassword: dcloud-repmgr-password-please-change
      repmgrUsername: repmgr
  postgresql:
    database: dcloud
    username: dcloud
    replicaCount: 2
    existingSecret: dcloud-database
    persistence:
      storageClass: ceph-rbd
  pgpool:
    image:
      repository: bitnamilegacy/pgpool
