image:
  registry: ghcr.io
  repositoryOwner: daigo-suhara
  pullPolicy: Always
  tag: latest

publicServiceDomain: drkatana.com

authentik:
  baseUrl: https://auth.daigo-suhara.com

storage:
  createClass: true
  className: ceph-rbd
  clusterID: rook-ceph
  pool: rbd

console:
  replicaCount: 1
  image:
    repository: console
  service:
    type: LoadBalancer
    port: 8080
  publicServiceDomain: drkatana.com
  publicHostname: cloud.daigo-suhara.com

api:
  replicaCount: 1
  image:
    repository: api
  service:
    port: 8000

project:
  replicaCount: 1
  image:
    repository: project
  service:
    port: 8081

container:
  replicaCount: 1
  image:
    repository: container
  service:
    port: 8082

database:
  image: postgres:16-alpine
  service:
    port: 5432
  auth:
    database: dcloud
    username: dcloud
    password: dcloud
  persistence:
    size: 1Gi
    storageClassName: ceph-rbd
