# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: container.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'container.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0f\x63ontainer.proto\x12\x13\x64\x63loud.container.v1\"\x07\n\x05\x45mpty\"\x0f\n\rHealthRequest\"D\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07service\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t\"\xb5\x01\n\x07Service\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05image\x18\x02 \x01(\t\x12\x0b\n\x03url\x18\x03 \x01(\t\x12\r\n\x05ready\x18\x04 \x01(\x08\x12\x0e\n\x06reason\x18\x05 \x01(\t\x12\x12\n\ncreated_at\x18\x06 \x01(\t\x12\x12\n\nupdated_at\x18\x07 \x01(\t\x12\x11\n\tnamespace\x18\x08 \x01(\t\x12\x12\n\nproject_id\x18\t \x01(\t\x12\x12\n\ngeneration\x18\n \x01(\x03\":\n\x13ListServicesRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\"\x80\x01\n\x14ListServicesResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x11\n\tnamespace\x18\x03 \x01(\t\x12\x30\n\ncontainers\x18\x04 \x03(\x0b\x32\x1c.dcloud.container.v1.Service\"\x8c\x01\n\x14\x44\x65ployServiceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\x12\x0c\n\x04port\x18\x05 \x01(\x05\x12\x11\n\tmin_scale\x18\x06 \x01(\x05\x12\x11\n\tmax_scale\x18\x07 \x01(\x05\"I\n\x14\x44\x65leteServiceRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x12\n\nproject_id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t2\xfc\x02\n\x10\x43ontainerService\x12Q\n\x06Health\x12\".dcloud.container.v1.HealthRequest\x1a#.dcloud.container.v1.HealthResponse\x12\x63\n\x0cListServices\x12(.dcloud.container.v1.ListServicesRequest\x1a).dcloud.container.v1.ListServicesResponse\x12X\n\rDeployService\x12).dcloud.container.v1.DeployServiceRequest\x1a\x1c.dcloud.container.v1.Service\x12V\n\rDeleteService\x12).dcloud.container.v1.DeleteServiceRequest\x1a\x1a.dcloud.container.v1.EmptyBDZBgithub.com/daigo-suhara/dcloud/internal/pb/containerpb;containerpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'container_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZBgithub.com/daigo-suhara/dcloud/internal/pb/containerpb;containerpb'
  _globals['_EMPTY']._serialized_start=40
  _globals['_EMPTY']._serialized_end=47
  _globals['_HEALTHREQUEST']._serialized_start=49
  _globals['_HEALTHREQUEST']._serialized_end=64
  _globals['_HEALTHRESPONSE']._serialized_start=66
  _globals['_HEALTHRESPONSE']._serialized_end=134
  _globals['_SERVICE']._serialized_start=137
  _globals['_SERVICE']._serialized_end=318
  _globals['_LISTSERVICESREQUEST']._serialized_start=320
  _globals['_LISTSERVICESREQUEST']._serialized_end=378
  _globals['_LISTSERVICESRESPONSE']._serialized_start=381
  _globals['_LISTSERVICESRESPONSE']._serialized_end=509
  _globals['_DEPLOYSERVICEREQUEST']._serialized_start=512
  _globals['_DEPLOYSERVICEREQUEST']._serialized_end=652
  _globals['_DELETESERVICEREQUEST']._serialized_start=654
  _globals['_DELETESERVICEREQUEST']._serialized_end=727
  _globals['_CONTAINERSERVICE']._serialized_start=730
  _globals['_CONTAINERSERVICE']._serialized_end=1110
# @@protoc_insertion_point(module_scope)
