# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import container_pb2 as container__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in container_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContainerServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/dcloud.container.v1.ContainerService/Health',
                request_serializer=container__pb2.HealthRequest.SerializeToString,
                response_deserializer=container__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.ListServices = channel.unary_unary(
                '/dcloud.container.v1.ContainerService/ListServices',
                request_serializer=container__pb2.ListServicesRequest.SerializeToString,
                response_deserializer=container__pb2.ListServicesResponse.FromString,
                _registered_method=True)
        self.DeployService = channel.unary_unary(
                '/dcloud.container.v1.ContainerService/DeployService',
                request_serializer=container__pb2.DeployServiceRequest.SerializeToString,
                response_deserializer=container__pb2.Service.FromString,
                _registered_method=True)
        self.DeleteService = channel.unary_unary(
                '/dcloud.container.v1.ContainerService/DeleteService',
                request_serializer=container__pb2.DeleteServiceRequest.SerializeToString,
                response_deserializer=container__pb2.Empty.FromString,
                _registered_method=True)


class ContainerServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def Health(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeployService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteService(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContainerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=container__pb2.HealthRequest.FromString,
                    response_serializer=container__pb2.HealthResponse.SerializeToString,
            ),
            'ListServices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServices,
                    request_deserializer=container__pb2.ListServicesRequest.FromString,
                    response_serializer=container__pb2.ListServicesResponse.SerializeToString,
            ),
            'DeployService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeployService,
                    request_deserializer=container__pb2.DeployServiceRequest.FromString,
                    response_serializer=container__pb2.Service.SerializeToString,
            ),
            'DeleteService': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteService,
                    request_deserializer=container__pb2.DeleteServiceRequest.FromString,
                    response_serializer=container__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'dcloud.container.v1.ContainerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('dcloud.container.v1.ContainerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContainerService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcloud.container.v1.ContainerService/Health',
            container__pb2.HealthRequest.SerializeToString,
            container__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcloud.container.v1.ContainerService/ListServices',
            container__pb2.ListServicesRequest.SerializeToString,
            container__pb2.ListServicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeployService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcloud.container.v1.ContainerService/DeployService',
            container__pb2.DeployServiceRequest.SerializeToString,
            container__pb2.Service.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteService(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/dcloud.container.v1.ContainerService/DeleteService',
            container__pb2.DeleteServiceRequest.SerializeToString,
            container__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
